### ISSUE TITLE
"Unknown command: -NVGBASE_SWITCH"

### ISSUE THREAD

**Issue by BadaBingBR** [JWalkerMailly/Gmod-NVGBase#2]
i managed to get specific googles on 2 binds in the splinter cell pack, but any time +NVGBASE_SWITCH is activated trough a bind this appears on console.

**Comment by JWalkerMailly** [comment]
Hi, is this hindering you in any way or is it simply something that pops in the console?

**Comment by BadaBingBR** [comment]
the command works fine, but it prints this on console. Same thing with -NVGBASE_TOGGLE being a "unknown command"

**Comment by JWalkerMailly** [comment]
Alright, thanks for the heads up. Its probably just something to do with the fact that the command starts with a "+". Will not fix since it does not break gameplay.
